spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/elk
    username: root
    password: 0000
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: lnA5kTRklfcA3U8plD7Bht3c5WTQEh4sm18JdkvyzlM=
